on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing notify
    steps:
      - name: Hello world action step
        id: hello
        uses: dasshit/myteam-notify@v1.0
        with:
          api-url: ${{ secrets.BOTAPI }}
          bot-token: ${{ secrets.BOTTOKEN }}
          chat-id: ${{ secrets.CHATID }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"