# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test and upload Python Package

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

jobs:
  tests:
    strategy:
      matrix:
        python-version: [ '3.7.x', '3.8.x', '3.9.x', '3.10.x' ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v13.1
        with:
          files: |
            async_icq/*.py
            tests/test_*.py
      - name: Run step if any of the listed files above change
        if: steps.changed-files-specific.outputs.any_changed != 'true'
        run: |
          echo "No files listed above has changed." & exit 1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Updating pip
        run: python -m pip install --upgrade pip
      - name: Installing test requirements
        run: pip install -r test_requirements.txt
      - name: Install pytest-annotate plugin
        run: pip install pytest-github-actions-annotate-failures
      - name: Run unit tests
        env:
          TOKEN: ${{ secrets.TOKEN }}
          API_URL: ${{ secrets.API_URL }}
          ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
        run: python -m pytest --asyncio-mode=strict --import-mode=append --verbose --numprocesses=8 tests/
  deploy:
    needs: tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        verbose: true
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
